### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by dianvscom** [Jumpst3r/printed-hw-segmentation#6]
1. http://wuersch.pillo-srv.ch/#/algorithm/5ff5b809fad531d7dc0f29c4  
this link cannot access
2. I use the sample pic on docker, but the result is not very good. can you tell me the reason.
![fcn_out_crf](https://user-images.githubusercontent.com/80150176/142961481-be39e785-0500-4fda-a34a-f92edea56878.png)

**Comment by Jumpst3r** [comment]
Hi !

For your first question, I do not manage the online demo -  thanks for pointing out the problem, I will get in touch with the responsible person to see if we can bring it back online.

For your second question: Is this a custom picture / scan ? If so the accuracy is dependent on the DPI / color settings used to create the image. Could you provide me the original input image you used ?

**Comment by dianvscom** [comment]
Hi， 
1. The first question is not the online demo link, it's about the algorithms 's link. 
2. I run it on docker, the source image
3
![456](https://user-images.githubusercontent.com/80150176/143662444-114222e9-7386-435e-862e-55f2dec8de8c.jpg)

**Comment by Jumpst3r** [comment]
Looking at the image I think that the non-white background is maybe causing problems, all the scans I used for training had uniform white backgrounds.  I suggest you try to pre-process your image first to make it more like the example image on the repo page. This algorithm performs binarization before passing the image to the model, I think maybe that part is not working well enough for your image since the contrast between the writing and background is not as pronounced.

The link you posted in your first question is the link to the online demo, for which I will try to contact the person responsible.
